### ISSUE TITLE
[znc] Error with log syntax

### ISSUE THREAD

**Issue by crazy-max** [munin-monitoring/contrib#675] opened 2015-11-11 16:09 UTC
Hi @Thor77,

I cannot use the znc munin plugin. I've got an error when i exec a `munin-run` :

```
Traceback (most recent call last):
  File "/etc/munin/plugins/znc_logs", line 85, in <module>
    data()
  File "/etc/munin/plugins/znc_logs", line 53, in data
    network, channel, file_date = filename_.split('_')
```

Here is my conf :

```
[znc_logs]
user znc
group znc
env.logdir /home/znc/.znc/moddata/log/
```

And a specific tree to log file :

`/home/znc/.znc/moddata/log/user/freenode/#znc/2015-11-11.log`

Thanks for your help

**Comment by crazy-max** [comment] 2015-11-11 16:09
Btw i'm on ZNC 1.6.1

**Comment by Thor77** [comment] 2015-11-11 20:50
I need the full traceback to debug this.
Please copy everything, at least the line with the actual Exception.
(I hope i will find some time to make my plugin work with later ZNC-versions soon... but that's definitely not related to this issue)

**Comment by crazy-max** [comment] 2015-11-11 22:15
Ok but how i can generate a full traceback ?
I type this command to "debug" the plugin : `munin-run --debug znc_logs config`

```
# Processing plugin configuration from /etc/munin/plugin-conf.d/3rdparty
# Processing plugin configuration from /etc/munin/plugin-conf.d/munin-node
# Setting /rgid/ruid/ to /121/1003/
# Setting /egid/euid/ to /121 121 1003/1003/
# Setting up environment
# Environment logdir = /home/znc/.znc/moddata/log/
# About to run '/etc/munin/plugins/znc_logs config'
graph_title Lines in the ZNC-log
graph_category znc
graph_vlabel lines/minute
graph_scale no
Traceback (most recent call last):
  File "/etc/munin/plugins/znc_logs", line 85, in <module>
    data()
  File "/etc/munin/plugins/znc_logs", line 53, in data
    network, channel, file_date = filename_.split('_')
ValueError: need more than 1 value to unpack
```

Is it enough ?

Otherwise I think I found where the problem came from.
From your perl script you search logs with this pattern :

`freenode_#znc_2015-11-11.log`

But on my ZNC version the logs are not in the root folder but in multi subfolders :

`freenode/#znc/2015-11-11.log`

Hope this helps

**Comment by Thor77** [comment] 2015-11-12 07:01
uh, damnit. then it's an issue with my outdated plugin after all. Hopefully i will find some time to fix it today, sry :/

**Comment by crazy-max** [comment] 2015-11-12 08:46
Ok thanks :)

**Comment by Thor77** [comment] 2015-11-12 21:08
Just finished the new version, will open a PR tomorrow after some further testing.
If you want to give it a shot, you can find the updated file [in my fork](https://github.com/Thor77/contrib/blob/updateZNCPlugin/plugins/znc/znc_logs.py).

**Comment by crazy-max** [comment] 2015-11-12 22:35
Ohh fast :)

`munin-run --debug znc_logs config`

```
# Processing plugin configuration from /etc/munin/plugin-conf.d/3rdparty
# Processing plugin configuration from /etc/munin/plugin-conf.d/munin-node
# Setting /rgid/ruid/ to /121/1003/
# Setting /egid/euid/ to /121 121 1003/1003/
# Setting up environment
# Environment logdir = /home/znc/.znc/moddata/log/
# About to run '/etc/munin/plugins/znc_logs config'
graph_title Lines in the ZNC-log
graph_category znc
graph_vlabel lines/minute
graph_scale no
```

No error but no ouput and my graphs are empty, is there a problem ?

**Comment by Thor77** [comment] 2015-11-13 06:01
oh, forgot to mention that (will definitely do that in README, but i'm still not sure if it's really a good idea. what do you think?): The seperator at the end of the logpath ($logdir) is not necessary anymore (maybe I should raise an Exception if the seperator is present?). And thats the reason, you have no output: it searches ``/home/znc/.znc/moddata/log//*/*/*.log`` for your logs

**Comment by crazy-max** [comment] 2015-11-13 10:13
You can use `os.environ.get('logdir').rstrip('/')` to always remove trailing slash.

And i have an other issue btw for multiple users. It's an imlprovement but it would be nice to have graphs for multiple suers :)
Example folder structure :
```
/home/znc/.znc/moddata/log/users
|
-- crazy
    | 
    -- network1
    |   | 
    |   -- #channel
    |       | 
    |       -- 2015-11-11.log
    | 
    -- network2
        | 
        -- #channel
            | 
            -- 2015-11-11.log
```

**Comment by sumpfralle** [comment] 2016-10-22 21:48
How is the current state of this bug?

**Comment by Thor77** [comment] 2016-10-22 22:02
Eh, currently not being worked on.
Just figured out someone rewrote my plugin nearly completely in #639.
Wasn't aware of that until now, so some bugs of this could be already fixed (the PR was merged before the creation of this issue, though).
Can you still reproduce these errors?

(tagging @darac here for further assistance as i'm not really familiar with the current codebase of the plugin after this PR)

**Comment by darac** [comment] 2016-10-23 11:26
This should now work. I reworked the plugin to (try to) detect whether the log files were using the old-style `network_channel_date` format, or the new style `user/network/channel/date` format and extract the same information from each. I would suggest @crazy-max give the new plugin a try and see if it works.

**Comment by sumpfralle** [comment] 2016-11-05 23:41
I assume it is fixed.

**Closed by sumpfralle** 2016-11-05 23:41 UTC
